// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Entities;

[Keyless]
public partial class Prudoct
{
    public int Id { get; set; }

    public int? CategoryId { get; set; }

    [StringLength(20)]
    public string Name { get; set; }

    [StringLength(100)]
    public string Description { get; set; }

    public int? Cost { get; set; }

    [StringLength(40)]
    public string Image { get; set; }
}